### PR TITLE
fix(select): remove @bind decorators from 'decko' because IE error

### PR DESCRIPTION
**Pull request by hopkins-tk**
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/wc-catalogue/blaze-elements/blob/master/docs/CONTRIBUTING.md#commit
- [ ] There are no linting errors and code is properly formatted (your run before push `yarn ts:format && yarn ts:lint:fix`)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Select does not work in IE.

**What is the new behavior?**
Select works in IE.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by hopkins-tk** [comment]
Partial replacement of https://github.com/wc-catalogue/blaze-elements/pull/246

**Comment by Hotell** [comment]
As stated yesterday I'm not willing to do CR as I'm to strict to someone taste. Also as was told this project is not huge like react so you can do whatever you like even don't send reviews I guess.

**Comment by hopkins-tk** [comment]
Unfortunately it is to fix your broken branch from https://github.com/wc-catalogue/blaze-elements/pull/231.

As it is your branch we won't be merging you anything to it.

I don't really care how you do it:
- whether you review/comment and than once fixed (if something is wrong) merge it
- or whether you redo everything by yourself once again in your branch directly - be my guest

But I expect https://github.com/wc-catalogue/blaze-elements/pull/231 to be fixed and merged by today 12:00 - it is a BLOCKING for further development and instead of trying to fix it we will spend time discussing it, but not actually doing anything?

12:00 (**12 AM CET**)

**Comment by Hotell** [comment]
So it's not a blocker in first place. I did someone others work on Friday, which resolved all blockers https://github.com/wc-catalogue/blaze-elements/pull/229

If we are going to work this way to set exact times to finish work I demand that every member of team is present on every meeting and standup.

cheers

**Pull request merged**
