### PR TITLE
Fixes boxing - Blaze global style

### PR DESCRIPTION
**Pull request by hopkins-tk**
Introduces & uses **generics.shared.scss** which is based on **~blaze/scss/generics.global.scss** with small tweak to be working in shadow DOM.

### CODE REVIEW

**Review by hopkins-tk — COMMENTED** [review]
This new version with **:host** is not working in Firefox - maybe Polyfill is missing.

**Comment by devopsmariocom** [comment]
AFAIK :host only worked with vanilla WC

CC: @hotell

**Comment by hopkins-tk** [comment]
So do you think I should go with `*` and `* *` version?

**Comment by hopkins-tk** [comment]
` *` and `* *` version works in IE as well, so I changed it back to it.

**Review by devopsmariocom — APPROVED** [review]
I don't like * * approach but seems that it's working solution for now so let's stick with that and we can replace it any time later

**Pull request merged**
